---
date: "2022-10-29"
excerpt: In this block, we'll use the postcards package to make a single 'about' home
  page with only R Markdown.
subtitle: Write and send a single postcard.
title: Basic principles
weight: 1
---

```{r opts, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "img/"
)
```

## Basic principles

A good organizational scheme: 

* **Enforces good habits**. The organization should constrain your workflow enough that you're forced to practice good coding and research practices.
* **Is reproducible**. The organization should cover the entire workflow, from raw data to polished figures. A naive observer should be able to understand the organization of the project and replicate the analysis with a minimum of effort.
* **Is interpretable**. The organization should be simple enough to be interpretable to a naive observer. It should be possible to send a project folder to a collaborator without needing to explain the data or code in detail.

In a lab setting, where you're likely to have many separate projects, and to be collaborating with other colleagues, there are a few other considerations. 

* The structure should be general and flexible. It's tempting to tailor the organization to the specific data or research question associated with a particular project, but this tends to result in projects with wildly different organizations, which defeats the purpose. Picking a general template and sticking with it -- even if it's clunky or awkward for an individual project -- makes it easier to collaborate, and easier to return to the project after taking a break.
* There should be a common interface for dealing with shared datasets. Having every member of a lab host separate copies of the data from a single experiment leads to inconsistencies between separate analyses and confusion over the authentic version of the raw data.